@startuml

start
:Вход в систему;
switch ( Выбор действия )
case ( Чтение )
switch ( Что просмотреть? )
    case ( Посещаемость )
      :Просмотр посещаемости студентов;
    case ( Расписания )
      :Просмотр расписаний групп;
    case ( Группы )
      :Просмотр состава групп;
    case ( Профили )
      :Просмотр профилей;
    endswitch
case ( Редактирование )
    :Выбор группы;
    :Редактирование информации о
    посещаемости студентов группы;
@enduml
