@startuml
left to right direction
skinparam packageStyle rectangle
actor &quot;Пользователь&quot; as User
package &quot;Система&quot; {
    usecase &quot;Вход в систему&quot; as UC_Login
    usecase &quot;Регистрация&quot; as UC_Register
    usecase &quot;Сброс пароля&quot; as UC_Reset
}
User --&gt; UC_Login
User --&gt; UC_Register
User --&gt; UC_Reset
@enduml